# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5uskVZLoqFCMpkWrRPa11lvuLGZJQm3
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir('/content/drive/MyDrive/'))

import pandas as pd

Varejo = pd.read_csv("/content/drive/MyDrive/Varejo.csv", sep=";")

Varejo = Varejo.loc[:, ~Varejo.columns.str.contains('^Unnamed')]

print(Varejo.columns)

print(Varejo.shape)
print(Varejo.dtypes)

# Verificando valores nulos
print("\nValores nulos:")
print(Varejo.isnull().sum())

# Verificando duplicatas
print("\nDuplicados:")
print(Varejo.duplicated().sum())

# Verificando categorias ausentes
print("\nCategorias ausentes:")
print((Varejo == "#N/D").sum())

# Substituindo categorias ausentes por "Sem Categoria"
if "#N/D" in Varejo["PR_CAT"].values:
    Varejo["PR_CAT"] = Varejo["PR_CAT"].replace("#N/D", "Sem Categoria")

# Verificando se ainda existem categorias "#N/D"
print("\n#N/D restantes:")
print((Varejo["PR_CAT"] == "#N/D").sum())

# Eliminando linhas completamente duplicadas porque representam registros repetidos na base
Varejo = Varejo.drop_duplicates().copy()

# fazendo a coluna DATA ir para o formato datetime
Varejo["DATA"] = pd.to_datetime(Varejo["DATA"], format="%d/%m/%Y")

# fazendo a coluna CL_FHL ir para interger
Varejo["CL_FHL"] = Varejo["CL_FHL"].astype(int)

# Criando o DataFrame final com os dados limpos
df_limpo = Varejo.copy()

df_limpo.to_csv("df_limpo.csv", index=False, sep=";")

# os dados CO_ID, CL_ID e PR_ID não serão convertidos pois são códigos indentificadores, portanto strings, apesar de para nós parecer um numero. O dado CL_EC também não, pois trata-se de uma lista. Não foi necessário transformar nenhum dado em float neste caso.

# Agrupando os itens pelo ID da compra
itens_por_compra = Varejo.groupby("CO_ID").size()

print(itens_por_compra.head())

#valor dos filhos do cliente
media = Varejo['CL_FHL'].mean()

print("\n Media ")
print(media)

mediana = Varejo['CL_FHL'].median()

print("\n Mediana")
print(mediana)

desvio_padrao = Varejo['CL_FHL'].std()

print("\n desvio padrão")
print(desvio_padrao)

moda = Varejo['CL_FHL'].mode()

print("\n moda")
print(moda)

maximo = Varejo['CL_FHL'].max()

print("\n máximo de filhos")
print(maximo)

minimo = Varejo['CL_FHL'].min()

print("\n mínimo")
print(minimo)

total = Varejo['CL_FHL'].count()

print("\n Contagem")
print(total)

Quartis1 = Varejo['CL_FHL'].quantile(0.25)
Quartis2 = Varejo['CL_FHL'].quantile(0.50)
Quartis3 = Varejo['CL_FHL'].quantile(0.75)

print("\n QUARTIS")
print("25%:")
print(Quartis1)
print("50%:")
print(Quartis2)
print("75%:")
print(Quartis3)

#padrões de agrupamento por gênero e compras por genero

# Agrupando os itens por gênero do cliente
genero_do_cliente = Varejo.groupby("CL_GENERO").size()

print("\n genero do cliente")
print(genero_do_cliente)

# Contando compras diferentes por gênero
compras_por_genero = Varejo.groupby("CL_GENERO")["CO_ID"].nunique()

print("\n compra por genero")
print(compras_por_genero)

"""Então nossas Conclusões são:

- A análise da coluna CL_FHL ajudou a entender melhor a quantidade de filhos dos clientes, usando cálculos como média, mediana, moda, mínimo, máximo e quartis.
- O agrupamento por CL_GENERO mostrou diferenças na quantidade de itens registrados entre os gêneros.
- Também foi possível analisar a quantidade de compras diferentes para cada gênero usando CL_GENERO e CO_ID.
- Foi possível perceber que o CO_ID pode aparecer várias vezes, porque cada linha representa um item de uma compra e não uma compra inteira.
- Na limpeza dos dados, foram removidas linhas duplicadas e a coluna DATA foi transformada para a forma de data.
- Os valores #N/D encontrados nas categorias foram substituídos por Sem Categoria.
"""